### ISSUE TITLE
Can no longer install docker-compose with pip

### ISSUE THREAD

**Issue by alexpdp7** [foutaise/texttable#1]
# pip install docker-compose
    ...
    Downloading/unpacking texttable>=0.8.1,<0.9 (from docker-compose)
      Could not find a version that satisfies the requirement texttable>=0.8.1,<0.9 (from docker-compose) (from versions: v0.8.3)
      Some externally hosted files were ignored (use --allow-external to allow).

**Comment by foutaise** [comment]
Should be fixed now.

Just moved texttable on github, and the PKGINFO / file archive was modified
on pypi to reflect the change. Pypi file archive was renamed texttable-v0.8.3.tar.gz,
but pip was unable to extract the right version from the filename:

> Ignoring link https://pypi.python.org/packages/source/t/texttable/texttable-v0.8.3.tar.gz#md5=a1b25ba3390492fb53fe05c7fcecdfa1 (from https://pypi.python.org/simple/texttable/), version v0.8.3 doesn't match >=0.8.1,<0.9

I've uploaded a new release (0.8.4) on pipy, with a suitable archive filename now.

**Comment by Grokzen** [comment]
@foutaise Would it be possible to remove the broken `texttable-v0.8.3.tar.gz` from pypi and rebuild a working release with a correct name of `texttable-0.8.3.tar.gz` or will pypi block that?
We have a need and possible other people also, to have `0.8.3` as a working release that we can download from pypi. Even if there is a newer release, this breaks backwards compatibility with code that has been frozen with the old release.

**Comment by foutaise** [comment]
Hi @Groken. I'm unable to setup a working release for version 0.8.3 under the name texttable-0.8.3.tar.gz, as pypi does not allow to reupload a removed file. As a workaround, I've removed the archive texttable-v0.8.3.tar.gz and uploaded a new one under the name texttable-0.8.3.zip. That's kinda ugly, but it should do the job.

**Comment by Grokzen** [comment]
Ye, it is kinda ugly but if it would work and fixes the problem, i would say, go for it :]
