### ISSUE TITLE
Can not add string "INFINITY" to table rows.

### ISSUE THREAD

**Issue by biyiklioglu** [foutaise/texttable#2]
This was initially submitted here: https://github.com/bufordtaylor/python-texttable/issues/16

---

If I add string "INFINITY" to a Texttable using add_row I get "inf" instead of the original string.
You can test this using something like this:

```
#!/usr/bin/env python

from texttable import Texttable

table = Texttable()
table.add_row( ["INFINITY","infinity"] )
print table.draw() + "\n"
```
Capitalization of the string does not matter and the result is:
```
+-----+-----+
| inf | inf |
+-----+-----+
```

This seem to be due to line [366] (https://github.com/foutaise/texttable/blob/master/texttable.py#L366)

```
 f = float(x)
```

float function converts string "infinity" to a [IEEE 754 Floating Point Special Value](https://www.python.org/dev/peps/pep-0754/)

texttable should use some other trick to check whether the cell data is a number or not.

**Comment by foutaise** [comment]
> texttable should use some other trick to check whether the cell data is a number or not.

You just have to specify the data type of the column explictly, as a text column.

```
from texttable import Texttable

table = Texttable()
table.set_cols_dtype(['t', 't'])
table.add_row( ["INFINITY","infinity"] )
print table.draw() + "\n"
```

Gives:

```
+----------+----------+
| INFINITY | infinity |
+----------+----------+
```
