### ISSUE TITLE
datetime entries trigger unhandled exception

### ISSUE THREAD

**Issue by csernazs** [foutaise/texttable#28]
Commit a696bbc286cda83f756232c96f7ab96977e34307 introduced the _to_float class method which tries to convert the given value to a float.

While handling ValueError is ok for strings which cannot be formatted, when this function gets a datetime object (or any other object which is not string) it gets TypeError from the float() call and it explodes during the formatting of the table.

This is the error I get:

```
  File "/home/zsolt/.local/lib/python3.5/site-packages/texttable.py", line 476, in _str
    return FMT[dtype](x, n=n)
  File "/home/zsolt/.local/lib/python3.5/site-packages/texttable.py", line 446, in _fmt_auto
    f = cls._to_float(x)
  File "/home/zsolt/.local/lib/python3.5/site-packages/texttable.py", line 402, in _to_float
    return float(x)
TypeError: float() argument must be a string or a number, not 'datetime.date'
```

By adding the following to the _to_float() function the problem can be fixed:
```python
        except TypeError:
            raise FallbackToText()
```
Alternatively, multiple exceptions can be caught by `except (ValueError, TypeError):`.

**Comment by foutaise** [comment]
Hi @csernazs,

Thanks for your feedback. It's fixed in release [v1.1.1](https://github.com/foutaise/texttable/tree/v1.1.1)
Regards,
