### ISSUE TITLE
Row cell exceeding max length, text not folded correctly?

### ISSUE THREAD

**Issue by CaledoniaProject** [foutaise/texttable#34]
I'm using the following code to create a table

```
		table = Texttable()
		table.set_cols_align(["r", "l"])
		# table.set_deco(Texttable.HLINES)
		table.add_rows([
			["Name", info['name']],
			["Description", info['description']],
			["Authors", ','.join(info['authors'])],
			["Disclosure Date", info['disclosure_date']],
			["References", "\n".join(references2list(info['references']))]
		], header = False)
```

And it ends up like this

![screen 2017-12-30 at 10 59 05](https://user-images.githubusercontent.com/1357701/34450855-9a80f626-ed50-11e7-92ec-822ba57a0975.jpg)

**Comment by CaledoniaProject** [comment]
Looks like unicode issue?

**Comment by foutaise** [comment]
Hi @CaledoniaProject 

Might be a unicode issue. Please provide an example that I can play with in order to investigate.

Regards,

**Comment by CaledoniaProject** [comment]
Minimal example 

[work.txt](https://github.com/foutaise/texttable/files/1594447/work.txt)

**Comment by foutaise** [comment]
It's linked to a poor handling of CJK characters by textwrap.
([cf issue 12568](https://bugs.python.org/issue12568)).

I have a working version based on CJKwrap, I'll make a new
release in a few days, that will use cjkwrap instead of texttable
if available.

**Comment by foutaise** [comment]
Hi @CaledoniaProject ,

Release [v1.2.0](https://github.com/foutaise/texttable/releases/tag/v1.2.0) should fix this issue. You'll have to install the cjkwrap library (pip install cjkwrap) as a dependency.

Regards,

**Comment by CaledoniaProject** [comment]
Thanks
