### ISSUE TITLE
max_width doesn't work, or I don't understant it

### ISSUE THREAD

**Issue by laboo** [foutaise/texttable#36]
I see text wrapping here. I'm trying to have the cells always occupy just one line and by cutting off the text that doesn't fit in the cell's width. Shouldn't max_width=0 do this, or am I misunderstanding? Thanks!
```python
from texttable import Texttable

table = Texttable(max_width=0)
table.set_deco(Texttable.HEADER)
table.set_cols_align(["l", "r", "c"])
table.set_cols_valign(["t", "m", "b"])
table.set_cols_width([10, 5, 3])
table.add_rows([["Name", "Age", "Nickname"],
                ["Mr Xavier Huon", 32, "Xav'"],
                ["Mr Baptiste Clement", 1, "Baby"],
                ["Mme Louise Bourgeau", 28, "Lou Loue"]])
print(table.draw() + "\n")
```

**Comment by foutaise** [comment]
Hi @laboo 

Using an explicit width for each column by calling 'set_cols_width' has precedence over max_width value. texttable never truncates cell content in any case.

Best regards.

**Comment by laboo** [comment]
Thanks @foutaise !
