### ISSUE TITLE
Non Uniform Cell

### ISSUE THREAD

**Issue by digital-idiot** [foutaise/texttable#37]
Will it be possible to support non-uniform cells in future?

**Comment by foutaise** [comment]
Hi @digital-idiot,

Could you be more explicit please? «Non uniform cell» does not ring a bell to me.
Best regards.

**Comment by digital-idiot** [comment]
Thanks for your prompt response. I'm talking about something like this: 
![non_uniform_table](https://user-images.githubusercontent.com/10576475/37879079-305ed960-3090-11e8-9fc8-05c7a187d5ad.png)

If at all this is possible, it would be nice have the flexibility.

**Comment by foutaise** [comment]
I see, you're asking for row/col spanning. No, I don't plan to implement that in the future.That would require a fair amount of work, and that would increase the API complexity. The statement mission of the project is «creating simple ASCII tables», so I try to stick to it.

You might try a combination of html table + links -dump as an alternative:

```
$ cat table.html 
<table border="1">
  <tr>
    <td>toto</td>
    <td>tutu</td>
  </tr>
  <tr>
    <td colspan="2">plop</td>
  </tr>
</table>

$ links -dump table.html
   +-------------+
   | toto | tutu |
   |-------------|
   | plop        |
   +-------------+
```

Regards,
