### ISSUE TITLE
Permission to generate stubs for texttable in typeshed

### ISSUE THREAD

**Issue by waseem18** [foutaise/texttable#40]
Hi Gérôme,

I would like to add stubs for _texttable_ to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the Python stdlib and popular third party libraries. As per PEP 484, permission is required from the library owner before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo

These stubs will be used by mypy and Pycharm. I'll start working on creating stubs after I get permission you.

Thanks

**Comment by foutaise** [comment]
Hi Wasim,

No problem, go ahead.

Regards,
