### ISSUE TITLE
NameError: name 'textwrapper' is not defined

### ISSUE THREAD

**Issue by discosultan** [foutaise/texttable#43]
After upgrading from v1.2.1 to v1.3.0, I receive the following error at https://github.com/foutaise/texttable/blob/f73470b81632068cc2c4eed6f9a43a64ea818c81/texttable.py#L660

```
NameError: name 'textwrapper' is not defined
```

Seems to be related to this commit: https://github.com/foutaise/texttable/commit/1c9bfd1823f10584fd6979013ef14a1a3d408b99#diff-6fcb6f9862ce4066ab0c20c4b4eba23bL127

Note that I do not have [cjkwrap](https://github.com/fgallaire/cjkwrap) installed.

**Comment by foutaise** [comment]
Hi @discosultan,

Thanks for your report, I didn't catch this bug as I had cjkwrap installed.
It's fixed in release 1.3.1.

Best regards.

**Comment by discosultan** [comment]
Thanks @foutaise
