### ISSUE TITLE
Allow deficient rows

### ISSUE THREAD

**Issue by slavkoja** [foutaise/texttable#44]
When i try to add row, which has not enough items, i got exception `texttable.ArraySizeError: array should contain X elements`. Please, allow to add rows and set options with partial array, which will be extended with desired defaults and leave exception only when there is more than needed amount of items.

**Comment by foutaise** [comment]
Hi @slavkoja ,

Sorry but I prefer to keep it that way, simple and explicit.
Implementing this functionnality would require dealing with
default substitution values, which would add clutter to the API.

If you need such functionnality, feel free to write a child class
of texttable that overwrite the add_row() method.

Regards,
