### ISSUE TITLE
Pre-github history lost

### ISSUE THREAD

**Issue by jayvdb** [foutaise/texttable#5]
Older releases are not available in the github history.

It would be nice to have at least the released versions in the git repository, especially since this older released versions of this package are included in distros.

This can be done in various ways, of which the best is `git symbolic-ref` or similar.

**Comment by jayvdb** [comment]
Older history also not on https://pypi.python.org/simple/texttable/ , which contains only 0.8.3 and 0.8.4

**Comment by foutaise** [comment]
I've uploaded releases up to 0.8.0 on pypi, for those who need access to some older releases.

**Comment by jayvdb** [comment]
Thanks.
