### ISSUE TITLE
Columns are not aligned correctly with terminal colors

### ISSUE THREAD

**Issue by fridex** [foutaise/texttable#53]
When using terminal colors the column with a colored text is not aligned correctly. The texttable's `len` method does not remove terminal control characters like color modifiers:

```python
In [1]: from texttable import len as texttable_len

In [2]: from termcolor import colored

In [3]: s = colored('ERROR', 'red')

In [4]: texttable_len(s)
Out[4]: 14

In [5]: s
Out[5]: '\x1b[31mERROR\x1b[0m'
```

**Comment by foutaise** [comment]
cf https://github.com/foutaise/texttable/issues/14.

Regards,
