### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by ZsemberiDaniel** [foutaise/texttable#55]
Hi!

I've been using your library and noticed that when I use an emoji in a cell, then the cell's width does not match with the other cells' widths which are in the same column. Is there any way to fix it or it's not possible? 

I took a closer look at the functions and I noticed that when for example it has a '😂' emoji, then it counts as 2, but a simple heart emoji is counted as 1.

Thanks in advance,
Daniel

**Comment by foutaise** [comment]
Hi @ZsemberiDaniel,

Last commit (https://github.com/foutaise/texttable/commit/ae1e4966da7c3daff537eabd49b67f44ecbe944a) should improve emoji support.

You'll have to install the the wcwidth library (pip install wcwidth) first. It won't provide
a full emoji support (rendering properly emoji is quite complex), but it's a step in the right
direction.

Let me know if it's ok on your side. A new release including this change will occur
in a few days.

Best regards,
