### ISSUE TITLE
python3readiness.org says texttable isn't ready for Python 3

### ISSUE THREAD

**Issue by petewood** [foutaise/texttable#56]
Hi, was wondering whether you're aware that `texttable` is one of only 4 libraries to not support Python 3 in the top 120-240 most popular Python libraries on http://py3readiness.org/.

I can see that you say you support Python 3 and was wondering why it's not showing up as supporting it.

The site https://caniusepython3.com also says you support it:

https://caniusepython3.com/project/texttable

**Comment by foutaise** [comment]
Hi @petewood,

I don't know why they report it as Python 3 incompatible. I opened an [issue](https://github.com/chhantyal/py3readiness/issues/58).

Thanks for your feedback.

**Comment by petewood** [comment]
Hi @foutaise,

Glad to help. The page looks amazing now, only one library out of the top 360 not compatible.

Thanks for your responsiveness, and your work on the library. Much appreciated.
