### ISSUE TITLE
Include tests in source tarball

### ISSUE THREAD

**Issue by jayvdb** [foutaise/texttable#58]
They were in 1.4, but disappeared in 1.6

**Comment by jayvdb** [comment]
Oh, and the LICENSE is also missing.

A changelog would also be nice ;-)

**Comment by jayvdb** [comment]
A bit of a changelog at https://build.opensuse.org/request/show/676269 to help you get started.

**Comment by foutaise** [comment]
Hi @jayvdb 

Thanks for your feedbacks. It's fixed as of release v1.6.1.

Best regards.

**Comment by jayvdb** [comment]
Thanks a lot.  That is now packaged into the devel area, which is the step before it goes to the wider openSUSE userbase.
