### ISSUE TITLE
If it is floating-point data, can the decimal digits be modified?

### ISSUE THREAD

**Issue by xianba** [foutaise/texttable#61]
![image](https://user-images.githubusercontent.com/11084189/61026513-1d3f3d00-a3e6-11e9-9076-a3dffe4dfe60.png)

**Comment by foutaise** [comment]
Hi @xianba 

You can use the set_precision() method to adjust the number of decimals digits.

Best regards,

**Comment by xianba** [comment]
That's perfect. Thank you.
