### ISSUE TITLE
Table header being reset should not "delete" data being added previously with .add_rows(header=True)

### ISSUE THREAD

**Issue by vmm86** [foutaise/texttable#62]
Hello and thanks for a useful Python package.

I've found a strange behaviour of an empty table with one row table data being added firstly with `table.add_rows(some_table_data)` and headers being  added after that with `table.header(header_data)`. Table looks like this:

```
+---------+---------+---------+---------+---------+
| Column1 | Column2 | Column3 | Column4 | Column5 |
+=========+=========+=========+=========+=========+
+---------+---------+---------+---------+---------+
```
It works this way because `.add_rows()` method has `headers` attribute with the default value of `True`. So the first row of table data is to be moved from table data to headers by default. But if we run a separate `.header()` method afterwards, then the header is to be replaced with the new header data, and the first row of table data (being passed as header previously) just disappears.

I don't think that's right. There are several possible ways to solve it:

1. The `header` attribute of `.add_rows()` method could be changed to False by default to prevent such a strange behavior. But it won't be possible if you'd like to maintain backwards compatibility.
2. It's possible to modify `.add_rows()` method to check if rows data size is one row only, and if it's true - not to move that row to header (with a possible console warning), or move it to header along with some console warning.
3. It's possible to modify `.header()` method to check if header has not been set yet (if it's empty), and if it's not - to move its data to first row of table data before replacement (with a possible console warning as well).

**Comment by foutaise** [comment]
Hi @vmm86,

If you call `.header()` after calling `.add_rows()` while header argument was True, it's normal that the header previously set is replaced.

To give a bit of context, at the beginning of the API, I provided only `.header()` and `.add_row()`. You're supposed to call `.header()` to set the header, then `.add_row()` in a loop to add data rows.

Then `.add_rows()` method has been added to create a table in one go from a list of rows, assuming by default that the first row specify the header of the table. 

So you either proceed using `.add_row()` like this:

```
table = Texttable()
table.header(["header a", "header b"])
for row in [[1, 2], [3, 4]]:
        table.add_row(row)
print(table.draw())
```
or using `.add_rows()` like this:

```
table = Texttable()
table.add_rows([["header a", "header b"], [1, 2], [3, 4]])
print(table.draw())
```
You can setup the header separately while using `.add_rows()`, just specify False as the header value:

```
table = Texttable()
table.header(["header a", "header b"])
table.add_rows([[1, 2], [3, 4]], False)
print(table.draw())
```

I understand your point of view as you view the .`add_rows()` method as a way to add data rows. But it's not the case, `.add_rows()` is designed to setup a table in one go, and by default the first row is the header row, not a data row. The only viable solution to match your requirements would be to apply your fix number 1. But as you mention, it would break backward compatibility. Therefore, I keep the API this way, to keep backward compatibility, and to stay consistent with the primary intention of the `.add_rows()` method.

Best regards,
