### ISSUE TITLE
Any plan on adding a wheel (.whl) to pypi?

### ISSUE THREAD

**Issue by dhruv-balakrishnan** [foutaise/texttable#65]
Just wondering if there's a possibility of uploading a wheel to pypi so I can use it as an official .whl file instead of making my own.

**Comment by foutaise** [comment]
Hi @dhruv-balakrishnan 

It's done. It might be removed later on if it's a pain in the ass. To be honest, I'm not a big fan of the whole python packaging nightmare.

Best regards,

**Comment by dhruv-balakrishnan** [comment]
Thanks a lot. Sounds good.
