### ISSUE TITLE
Lines only every Nth row or column

### ISSUE THREAD

**Issue by hernot** [foutaise/texttable#69]
Sometimes it would be nice to have horizontal lines not every line or vertical lines not every column but just every eg 5th row or column.
Or at least the possibility to add a row which contains a sigle string to be repeated as hline or a list with alternating strings and None where the None items mark where the data would be and the strings indicate the vlines sort of.

**Comment by foutaise** [comment]
Hi @hernot,

That's out of the scope of this project, that claim to create "simple ASCII tables".

Creating tables with specific horizontal or vertical lines, at specific locations would
require a wider and more complex API. I believe that the success of this library comes
from its simplicity, and I want to keep it this way. 

Best regards.
