### ISSUE TITLE
PyPI doesn't have a copy of 0.8.5, please upload one

### ISSUE THREAD

**Issue by opello** [foutaise/texttable#7]
The latest version appears to be 0.8.5 (tagged and released here).  Please also upload 0.8.5 to PyPI so pip/easy_install can find it too.

Similar to [this issue](https://github.com/pypa/pypi-legacy/issues/434) I think, where https://pypi.python.org/pypi/texttable/ shows something different than the latest version shown on https://pypi.python.org/simple/texttable/.

**Comment by foutaise** [comment]
Thanks for your report, sorry I indeed forgot this part. That's fixed now.

**Comment by opello** [comment]
Thanks!
