### ISSUE TITLE
Table cell shows long numbers in scientific notation

### ISSUE THREAD

**Issue by Sibicoder** [foutaise/texttable#71]
**Issue:**
If one column of table cells has large integers (like epoch timestamp), the numbers are shown in scientific notation instead of original notation while printing

**Sample code:**

```
from texttable import *
table_list = Texttable(250)
table_list.header(["Attribute", "Actual"])
# <texttable.Texttable object at 0x102a0cb50>
client_count_ts = [{'client_count': 4, 'timestamp': 1606289700},
...  {'client_count': 4, 'timestamp': 1606290000},
...  {'client_count': 4, 'timestamp': 1606290300},
...  {'client_count': 4, 'timestamp': 1606290600},
...  {'client_count': 4, 'timestamp': 1606290900},
...  {'client_count': 4, 'timestamp': 1606291200},
...  {'client_count': 4, 'timestamp': 1606299900}]

for idx in range(0,len(client_count_ts)):
...     keys = client_count_ts[idx].keys()
...     for key in keys:
...         table_list.add_row([key, client_count_ts[idx][key]])

out = table_list.draw()
```

**Actual Output**

+--------------+-----------+
|  Attribute   |  Actual   |
+==============+===========+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1.606e+09 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1.606e+09 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1.606e+09 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1.606e+09 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1.606e+09 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1.606e+09 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1.606e+09 |
+--------------+-----------+
>>> 

**Expected output**

+--------------+-----------+
|  Attribute   |  Actual   |
+==============+===========+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1606290000 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1606290300 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1606290600 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1606290900|
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1606291200 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1606291200 |
+--------------+-----------+
| client_count | 4         |
+--------------+-----------+
| timestamp    | 1606299900 |
+--------------+-----------+

**Comment by foutaise** [comment]
Hi @Sibicoder 

Use an explicit call to set_cols_dtype() to force int representation.
By default, in auto formatting, if a number is > 1e8, scientific notation
is used.

```
from texttable import *

table_list = Texttable(250)
table_list.header(["Attribute", "Actual"])
table_list.set_cols_dtype(["i", "i"])

client_count_ts = [{'client_count': 4, 'timestamp': 1606289700},
    {'client_count': 4, 'timestamp': 1606290000},
    {'client_count': 4, 'timestamp': 1606290300},
    {'client_count': 4, 'timestamp': 1606290600},
    {'client_count': 4, 'timestamp': 1606290900},
    {'client_count': 4, 'timestamp': 1606291200},
    {'client_count': 4, 'timestamp': 1606299900}]

for idx in range(0,len(client_count_ts)):
    keys = client_count_ts[idx].keys()
    for key in keys:
        table_list.add_row([key, client_count_ts[idx][key]])

out = table_list.draw()
print(out)
```

gives the expected output:

```
+--------------+------------+
|  Attribute   |   Actual   |
+==============+============+
| client_count | 4          |
+--------------+------------+
| timestamp    | 1606289700 |
+--------------+------------+
| client_count | 4          |
+--------------+------------+
| timestamp    | 1606290000 |
+--------------+------------+
| client_count | 4          |
+--------------+------------+
| timestamp    | 1606290300 |
+--------------+------------+
| client_count | 4          |
+--------------+------------+
| timestamp    | 1606290600 |
+--------------+------------+
| client_count | 4          |
+--------------+------------+
| timestamp    | 1606290900 |
+--------------+------------+
| client_count | 4          |
+--------------+------------+
| timestamp    | 1606291200 |
+--------------+------------+
| client_count | 4          |
+--------------+------------+
| timestamp    | 1606299900 |
+--------------+------------+
```

Best regards.
