### ISSUE TITLE
not support utf-8 character

### ISSUE THREAD

**Issue by a22349** [foutaise/texttable#74]
hi , when i use utf-8 character , the format is false . i want the cell can wrap correctly . thanks for help .

from texttable import Texttable
table = Texttable()
table.set_cols_align(["l", "r", "c"])
table.set_cols_valign(["t", "m", "b"])
table.add_rows([["Name", "Age", "Nickname"],
                ["MrB aptiste Clement MrB aptiste Clement MrB aptiste Clement MrB aptiste Clement", 32, "lee'"],
                ["人民人民人民人民人民人民人民人民人民人民人民人民人民人民人民人民人民人民人民人民人民", 32, "tom'"],
])

+--------------------------------+--------------------------------+--------------------------------+
|              Name              |              Age               |            Nickname            |
+================================+================================+================================+
| MrB aptiste Clement MrB        |                                |                                |
| aptiste Clement MrB aptiste    |                             32 |                                |
| Clement MrB aptiste Clement    |                                |              lee'              |
+--------------------------------+--------------------------------+--------------------------------+
| 人民人民人民人民人民人民人民人民人民人民人民人民人民人民人民 |                             32 |                                |
| 人民人民人民人民人民人民       |                                |              tom'              |
+--------------------------------+--------------------------------+--------------------------------+

**Comment by foutaise** [comment]
Hi @a22349,

As specified in the documentation, you should install the cjkwrap library
for better wrapping of CJK text.

Best regards.
