### ISSUE TITLE
`texttable.pyi` file missing when installed via pip

### ISSUE THREAD

**Issue by ddalcino** [foutaise/texttable#82]
I see that someone has taken the trouble to add a very nice `texttable.pyi` file to this project, and included it in `MANIFEST.in`. I can also see that the `texttable.pyi` file is present in the `texttable-x.x.x.tar.gz` file available at https://pypi.org/project/texttable/#files.

However, when I install `texttable` in a venv using `pip install texttable` (pip is version 22.3.1), `mypy` cannot locate the `texttable.pyi` file, and neither can I. In my `venv/python3.10/site-packages` folder, I have lots of libraries in their own folders, and one `texttable.py` file on its own, without any folder. There's a `texttable-1.6.4.dist-info` folder, but it includes metadata and no `.pyi` file.

This might be a bug for `pip` rather than a bug for `texttable`, but I thought I would bring it to your attention first. It could be easier to fix the problem by packaging `texttable` a different way, rather than changing `pip`.

**Comment by foutaise** [comment]
Hi ddalcino,

OK, yet another surprise with pip tooling/packaging. I really hate python packaging.
Anyway, I've just released a new version (1.6.5) that will include the missing file.

Best regards.

**Comment by foutaise** [comment]
FYI: https://github.com/foutaise/texttable/issues/84
