### ISSUE TITLE
1.6.6 installs a file into /usr/stub/texttable.pyi

### ISSUE THREAD

**Issue by juippis** [foutaise/texttable#84]
Never seen `/usr/stub` being used before, so I guess this is a bug? Then again I'm not too familiar with python packaging (or at all).

1.6.5 had it, I guess properly installed, here:
```
/usr/lib/python3.10
/usr/lib/python3.10/site-packages
/usr/lib/python3.10/site-packages/__pycache__
/usr/lib/python3.10/site-packages/__pycache__/texttable.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/__pycache__/texttable.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/__pycache__/texttable.cpython-310.pyc
/usr/lib/python3.10/site-packages/texttable-1.6.5.dist-info
/usr/lib/python3.10/site-packages/texttable-1.6.5.dist-info/METADATA
/usr/lib/python3.10/site-packages/texttable-1.6.5.dist-info/RECORD
/usr/lib/python3.10/site-packages/texttable-1.6.5.dist-info/WHEEL
/usr/lib/python3.10/site-packages/texttable-1.6.5.dist-info/top_level.txt
/usr/lib/python3.10/site-packages/texttable.py
/usr/lib/python3.10/site-packages/texttable.pyi
```

**Comment by foutaise** [comment]
Hi @juippis,

Thanks for the feedback. I wanted to include the stub file texttable.pyi into the wheel package,
but the packaging made in v1.6.5 generated issues with python2.x releases at least.
I thought v1.6.6 would be ok but obviously not. 

I get rid of it for the moment. python packaging really drives me crazy. I would have
to rework my packaging entirely to include this superfluous file.

Anyhow, v1.6.7 should be fine.

Best regards.

**Comment by mgorny** [comment]
If I recall correctly, the only way to do that would be to convert `texttable` into a package. This should be doable in backwards compatible way, though, basically:

```
mkdir texttable
git mv texttable.py texttable/__init__.py
git mv texttable.pyi texttable/__init__.pyi
> texttable/py.typed
git add texttable/py.typed
```

Please don't take my word for it, though.

**Comment by juippis** [comment]
Thanks for the very swift fix!
