### ISSUE TITLE
How to create a tight table?

### ISSUE THREAD

**Issue by smprather** [foutaise/texttable#86]
I would like to have a single blank column between each cell. The column width should auto-shrink wrap, right?

I have tried `table.set_deco(0)` and `table.set_chars(["", "", "", ""])`. But I still get something like this:
```
Total Internal Power:   303.380   65.838%
```

How can I get the column separator down to a single space? Thanks!! (Note: `table.set_cols_dtype(["t", "t", "t"])`. I am formatting the floats myself w/ f=strings.)

**Comment by foutaise** [comment]
Hi @smprather,

That's the tightest you can achieve. Code should be modified to tighten even more
the rendering when no VLINES are used. When VLINES are enabled , the cell separator
is 3 chars wide (space, VCHAR, space). You expect to get a single space separator without
VLINES, but I decided from the beginning to replace VCHAR by a space in such a case,
and use therefore a 3 spaces cell separator.

That's a rendering decision made from the beginning, as I felt that the rendering was
more readable this way. Therefore I won't change the code to tighten event more the
rendering.  Another reason for not changing the code is that a lot of people rely on this
library, nobody ever complained about this decision, and modify the rendering mechanism
now would disturb a lot of users.

Please find hereafter a diff of the code that need to be changed to suit your needs just in case:

```
@@ -574,8 +574,10 @@ class Texttable:
         if (is_header):
             horiz = self._char_header
         # compute cell separator
-        s = "%s%s%s" % (horiz, [horiz, self._char_corner][self._has_vlines()],
-            horiz)
+        if self._has_vlines():
+            s = "%s%s%s" % (horiz, self._char_corner, horiz)
+        else:
+            s = horiz
         # build the line
         l = s.join([horiz * n for n in self._width])
         # add border if needed
@@ -683,7 +685,10 @@ class Texttable:
                 else:
                     out += cell_line + fill * space
                 if length < len(line):
-                    out += " %s " % [space, self._char_vert][self._has_vlines()]
+                    if self._has_vlines():
+                        out += " %s " % self._char_vert
+                    else:
+                        out += " "
             out += "%s\n" % ['', space + self._char_vert][self._has_border()]
         return out

```

Hope you'll understand my decision. Thanks for your report.
Best regards.

**Comment by smprather** [comment]
Thanks for the thorough explanation and patch code! To be clear, I wasn't recommending making a default change that would impact current users. I was hoping it could be an opt-in change.

This further reinforces my feeling that I need contribute a text table generator of my own. I can't find any that do everything, including row and column spanning. I would probably start with a direct port of the Ruby terminal-table and add row-spanning. Thanks again Gerome!
