### ISSUE TITLE
Ansi color codes

### ISSUE THREAD

**Issue by jonndoe47pp** [foutaise/texttable#88]
How do I use ansi color codes in a cell without the cell alignment (and the header alignment) getting out of sync, in other words I want to use:

    g = "\033[38;2;255;255;0m"
    y = "\033[38;2;000;255;0m"

But when I add them to the first column (at the start) it shifts everything. Any ideas where/how I add these in?

As texttable doesn't recognise that ansi color codes don't move the cursor  argg... You understand I hope.

Yes, I know I can "fudge" it by adding to the header the color code but still the width of the color codes if computer as part of the width of the column. So, everything is still wrong as I cannot "use" that width for actual content.

**Comment by foutaise** [comment]
Hi @jonndoe47pp,

No plan to support any ansi escape codes, as they are not supported by every terminal,
on every operating systems. I already provided the same answer regarding color
support (cf https://github.com/foutaise/texttable/issues/14). As a maintainer, I want to keep this library simple, portable, and easy to maintain.

Best regards.

**Comment by shotah** [comment]
Pretty sure this isn't about support for ansi escape codes as much as it its for them to be ignored in length calculation. This sounds like just lack of support for the library. It'd be pretty easy and universal to add some regex scrubbers for when you calculate length.

Something like: 
https://stackoverflow.com/questions/14693701/how-can-i-remove-the-ansi-escape-sequences-from-a-string-in-python
