### ISSUE TITLE
texttable can't handle unicode in the header

### ISSUE THREAD

**Issue by pjmcdermott** [foutaise/texttable#9]
See the example below of trying to set a Unicode string in the header:

```
Python 2.7.10 (default, Nov 23 2015, 17:54:48) 
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from texttable import Texttable
>>> tt=Texttable()
>>> pound=u'£'
>>> type(pound)
<type 'unicode'>
>>> print pound
£
>>> tt.add_rows([['Test', pound]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.local/lib/python2.7/site-packages/texttable.py", line 353, in add_rows
    self.header(rows[0])
  File "/home/paul/.local/lib/python2.7/site-packages/texttable.py", line 320, in header
    self._header = list(map(str, array))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 0: ordinal not in range(128)
```

This is with texttable 0.8.6 on python 2.7.10. I have (tardily) just upgraded from texttable 0.8.1, and I did not see this issue on the previous version.

If I look at line 320 in header(), I can't understand the reason for

`self._header = list(map(str, array))`

versus:

`self._header = list(array)`

or even:

`self._header = array`

and making the header input requirement simply "a list of strings".

While I am no Unicode/encoding/decoding expert, I think the Texttable class should handle valid python strings, and the user be responsible for encoding and decoding the output.

**Comment by foutaise** [comment]
Thanks for your report, should be fixed in the last release (0.8.7).
