### ISSUE TITLE
Fix calculate length by dropping un-printable characters

### ISSUE THREAD

**Issue by shotah** [foutaise/texttable#90]
Currently column width is impacted by non-printable characters. Would be extremely nice to see this supported and add to the flexibility of this highly used module. 

Using something like regex to remove characters that wont be printed would greatly enhance this modules flexibility while maintaining its support for its many systems.

Examples of Regex to remove encoding characters: 
https://stackoverflow.com/questions/14693701/how-can-i-remove-the-ansi-escape-sequences-from-a-string-in-python

Other options include switching encoding to have the characters dropped while calculating length.

**Comment by foutaise** [comment]
Hi @shotah,

I won't waste my time trying to filter non-printable characters.

The link you mention is a proof that filtering un-printable chars is
not an easy task. You can use a regexp to filter some ansi codes,
but plenty of corner cases won't be handled properly.

I don't want to maintain a superficial solution that would raise
many issues.

Best regards.
